import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>hell oworld</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-mono px-6 py-4">
        <h1>
          Welcome to <a href="https://nextjs.org">Scifi-UI</a>
        </h1>

        <h2 className="mb-12">
          <a href="https://nextjs.org/learn">
            Recreating UIs from film and television
          </a>
        </h2>
        <Link href="/replicant-cards">
          <p className="cursor-pointer">Blade Runner</p>
        </Link>
      </main>

      <footer className="mt-auto"></footer>
    </div>
  );
}
